// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeatbuKq1_cZYp3F07fgLNqP6SzlzKB9k',
    appId: '1:747273541838:web:dd71e71b6e72c79866189f',
    messagingSenderId: '747273541838',
    projectId: 'templeapp-1f368',
    authDomain: 'templeapp-1f368.firebaseapp.com',
    storageBucket: 'templeapp-1f368.firebasestorage.app',
    measurementId: 'G-1YKSW3M1Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIKDB6o_yYabdISNyJAkTz9vvAR-6tTI',
    appId: '1:747273541838:android:c0e49bcdd506375c66189f',
    messagingSenderId: '747273541838',
    projectId: 'templeapp-1f368',
    storageBucket: 'templeapp-1f368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOpAb0BreMs7ZGS2vDqXyimDWs8q6MRWA',
    appId: '1:747273541838:ios:ebda8a3fb1b96f9c66189f',
    messagingSenderId: '747273541838',
    projectId: 'templeapp-1f368',
    storageBucket: 'templeapp-1f368.firebasestorage.app',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOpAb0BreMs7ZGS2vDqXyimDWs8q6MRWA',
    appId: '1:747273541838:ios:ebda8a3fb1b96f9c66189f',
    messagingSenderId: '747273541838',
    projectId: 'templeapp-1f368',
    storageBucket: 'templeapp-1f368.firebasestorage.app',
    iosBundleId: 'com.example.templeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeatbuKq1_cZYp3F07fgLNqP6SzlzKB9k',
    appId: '1:747273541838:web:807c9f28571a595666189f',
    messagingSenderId: '747273541838',
    projectId: 'templeapp-1f368',
    authDomain: 'templeapp-1f368.firebaseapp.com',
    storageBucket: 'templeapp-1f368.firebasestorage.app',
    measurementId: 'G-8DF4FNZMP1',
  );

}